# tpm2-tss (ESAPI + TCTI loader + marshalling). SWPASSKEY_TPM auto-ON when
# pkg-config finds the libraries; the build never hard-fails without them.
find_package(PkgConfig)
if(PkgConfig_FOUND)
  pkg_check_modules(TSS2_ESYS IMPORTED_TARGET tss2-esys)
  pkg_check_modules(TSS2_TCTILDR IMPORTED_TARGET tss2-tctildr)
  pkg_check_modules(TSS2_MU IMPORTED_TARGET tss2-mu)
  pkg_check_modules(TSS2_RC IMPORTED_TARGET tss2-rc)
endif()
if(NOT DEFINED SWPASSKEY_TPM)
  if(TSS2_ESYS_FOUND AND TSS2_TCTILDR_FOUND AND TSS2_MU_FOUND AND TSS2_RC_FOUND)
    set(SWPASSKEY_TPM ON)
  else()
    set(SWPASSKEY_TPM OFF)
  endif()
endif()
option(SWPASSKEY_TPM "Build the TPM 2.0 ESAPI key backend" ${SWPASSKEY_TPM})
if(SWPASSKEY_TPM AND NOT (TSS2_ESYS_FOUND AND TSS2_TCTILDR_FOUND AND TSS2_MU_FOUND AND TSS2_RC_FOUND))
  message(FATAL_ERROR "SWPASSKEY_TPM=ON but tss2-esys/tss2-tctildr/tss2-mu/tss2-rc were not found (pkg-config)")
endif()
message(STATUS "TPM 2.0 key backend: ${SWPASSKEY_TPM}")
